[package]
name = "fluxcut-media"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
fluxcut-diagnostics.workspace = true
fluxcut-hardware.workspace = true
fluxcut-project.workspace = true
fluxcut-cache.workspace = true
fluxcut-ffmpeg-core.workspace = true
crossbeam-channel.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
